language: java

# Ubuntu Xenial (https://docs.travis-ci.com/user/reference/xenial/)
dist: xenial

jdk: openjdk11

jobs:
  include:
    - stage: test
      if: (NOT branch =~ /^release\/.*$/)
      script: mvn --batch-mode test
      after_success: mvn --batch-mode jacoco:report coveralls:report
    - stage: release
      if: (branch =~ /^release\/.*$/)
      env:
        - GIT_USERNAME=daniel-shuy
        # GIT_PASSWORD
        - secure: DGfQGdyii30XppqdTyLQCZgK2Uhy6FC3YUXBo0I3u1dfMApEjRIxQlZC1+uGn/sp9V5iSbNsWreh7FbMLGrEpG60l+vf/RFE5z29i8fbS6xq12X/JXTY7Bvu85Cgms0AXCFV5qELOh/ItBTY5Sn5dyB5oFazlOxSYNwDKxxcY7z83yHRrOn8BBXdZ6S0wAhqmGODFjWa6ryIhC+Tx5IzjAILPXs0Z5Zjr/kK6Zc9z5qlVg+FONBa0s6rr41g1skFGIaNSlGVFToaUAd0FyK0QZ6VKXhMOkOgmgBvGx+/wZfOEIVEeb+PMM4NHsGJLMD4Dc/TcY9vG0WcdHDQbnLDuNf5u/3h8iCBMQMce+HgT32b1AOVUN652f8fab8D3wkJD9kxBWk/y4CDWVDtN2R+lDRqAAAiVFaLEBHmFDijZo4OV9Tz7Bo8lnCcuKGy4lQHQ0nFjK/ZlgDyPNPAAZwSm8451g+MMOVZ2JRFXlMHeLftVUiNCNLkUD/DWfZTK/50YHDA3MmFwBSeZ/yoxhDPI1774b0FcOW6HnsPCurKYzvUI7muDAcGbZn0oayDsOflzDneAR9T4NLS7F+EwyAe+gxNf3Ba5618wkmn3h9mo/p3JRbM6bK0SL4Ci4mXnFD0qWhc/z+1QXRPpTS8EN3uIz8Pl3gjv2cfUxayT0CFnqA=
        - OSSRH_USER=daniel-shuy
        # OSSRH_PASSWORD
        - secure: 5gullv5aDjCvPRJXQToOtrK+J76dCDgsfgrgCovRIpuvz7ToRGu43Gg1c/+zcayEFaglPdPrXUMR/5eyLyK5cuoIVGJUmTADL7o18IN3WRZCUNszUlujiiuEcv2QsyAmR2meJUs4pES5hiuxcQNluzcI1b8u/pXcosyWfY9MYKAMupyxQVfnCG9jLHi6QszARhYqwcnfFWdFBt7N8+hAvqVzJE5p3g4aueRWiYYMG0feTSdytDcHurL75Rlh74teZ5EXD3QM+bO2AUnpvkr6EaBsuuCAwSBRMJXxkljyLhZb9uhGoZ/EwDtSVwa86axLxJiixwFl44jY2Z1ub3nP3Z0XCN2alhkIHt3q8DSDzdze4NibivIQ5EUo7rOxLLXbYvB1Kf9q6lL7CdPWNI+U0x1/pmYU+jMuUqjmUicHW9/f0xI4OuEmX2u+rAj04Wctuwq/1qJe2Ejz8bNtjXU41XYJJRZNqCHWurAIyWU2ze0ZXnE4jvrJfnESnGpMopp/mve9pccYxFRWQUt8W3nUkTRu92fi1aXeruq9hnCoXEZ1/v/Mc/u2FWil5s5+7o4Z0k36vJdKPG3PGHHy1m+flRmDiHRTTbOKwqyjdR+F7tIhnRnkZ7NvDa8X4xb/WImIJTyhPDyacxQfAxdBnBpTYgrd5gS84y+agCZDG3TCb6g=
        # GPG_PASSPHRASE
        - secure: cZkBSEUzdlbaRwiPjEkKS3xKU8OLAgiBcnFK/wvBM6QajWA7mBS8Ji/0/lW5r1sV3aUNarqUgbXh2dpdLQ/BIZqWnTh+ExGCR7RCn9zDYIZ8Fzm0gLqFAlqFK9KcJrHGQat74zSfqjKj+xRxIgaRfbBq/bS5GRIv/C1N13K52eas8q25fcpYjj3Z1ibARM3sj8IjRO93FTAUAWRFS3OjJqhgqmYawT4Ys8+sNad+QE9r/alikWRYqhtwfw0IzBmAptY42qCLBwvCqbMifD2nCGr9NqaanBRUFjbAwhhCmkqgt+cAZudb4bKKAESID9LlQaPLclrT5CEkLSWfO5gjv9eb8ovrj7dUmqX0MIMgKtznBIZFnXTfPiNXJK7EA1zvMNAnzazG8MJOOZ/DaiU6SRkPe+LtERRI48vNhpY1gDceDQioxTbbwEXbZGlp4eROCKF3sfmF/283OqRkIuYqBnduFO3mcrMiqWc7WksyvzX9mp6+gnTqEXfwwoHFLNK6SodUEH5DsyR0tXfHh1qz6Ya3CoDC7Mw0BhAQQOcuenY8DKWfx3DUoahP0FzcddRCM1nULaxRKMNQu4SzfbVHM+RagsfvmShJpquc+LScEV9HaXT+mIwgtbd2izpkgbUfyQX13cIZw5ovPfKESX7Ktv8i2Q5yNPrkmV6FyOAz8sg=
        - GPG_PUBLIC_RING=travis/pubring.asc
        - GPG_SECRET_RING=travis/secring.asc
        # Extract release version from branch name
        - RELEASE_VERSION=`echo $TRAVIS_BRANCH | sed --regexp-extended 's/^release\/(.*)$/\1/'`
        - GIT_MERGE_AUTOEDIT=no
      before_install:
        # git-flow AVH (https://github.com/petervanderdoes/gitflow-avh/wiki/Installing-on-Linux,-Unix,-etc.#user-content-ubuntu)
        - sudo add-apt-repository --yes ppa:pdoes/gitflow-avh
        # use add-apt-repository --update in Ubuntu 17+ (Artful)
        - sudo apt-get update
        - sudo apt-get --yes install git-flow
        # https://docs.travis-ci.com/user/encrypting-files/#encrypting-multiple-files
        - openssl aes-256-cbc -K $encrypted_4c43ee4cec95_key -iv $encrypted_4c43ee4cec95_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d
        - tar xv -C travis -f travis/secrets.tar
        - cp travis/settings.xml $HOME/.m2/settings.xml
      install:
        - git remote set-url origin https://$GIT_USERNAME:$GIT_PASSWORD@github.com/$TRAVIS_REPO_SLUG.git
        - git remote set-branches --add origin master
        - git remote set-branches --add origin develop
        - git fetch origin
        - git checkout --force -b master --track origin/master
        - git checkout --force -b develop --track origin/develop
        - git checkout --force $TRAVIS_BRANCH
        - git config gitflow.prefix.release release/
        - git flow init --defaults
      script: mvn --batch-mode -DreleaseVersion=$RELEASE_VERSION release:prepare release:perform
      # --message option is required to suppress editor prompt
      after_success:
        - mvn --batch-mode jacoco:report coveralls:report
        - git flow release finish --showcommands --push --message 'Release' --notag

# Cache Maven dependencies (https://docs.travis-ci.com/user/caching/#arbitrary-directories)
cache:
  directories:
    - $HOME/.m2
